### ISSUE TITLE
How to get messages from packets?

### ISSUE THREAD

**Issue by arlomedia** [sammysmallman/CoreOSC#16]
Can someone show  how to get an OSCMessage from the OSCPacket that the client and server callback functions deliver?

The OSCKit ReadMe shows the callback functions but with no code inside. [This issue](https://github.com/sammysmallman/CoreOSC/issues/2) shows a cast from OSCPacket to OSCBundle, but Xcode tells me that will always fail, and if I try it anyway it does fail. I'm looking at the source code for OSCPacket, but I don't understand what it's doing. When I search the web, I just find other projects that also use the OSCKit, OSCCore or OSCPacket names.

I can see from the debugger output below that the message data I'm looking for is right there in the OSCPacket, but I can't find the syntax for getting it.

![Screenshot 2024-12-12 at 4 51 54 PM](https://github.com/user-attachments/assets/fe8979cd-4031-4a4c-9fe3-9e7ab2825ec6)

**Comment by arlomedia** [comment]
Searching through the source code, I found `let message = OSCKit.message(for: packet)`, but Xcode won't compile that and says `'message' is inaccessible due to 'internal' protection level`. That seems to only process OSCKit's address patterns anyway.

OSCPacket.data() seems more relevant, but the `.message(message)` syntax is confusing. I think it's just checking the type of the packet data and returning it as message data or bundle data.

I can convert that data to a string and then feed it into `OSCMessage(raw: messageString)`, but that doesn't separate the arguments from the address pattern. Or I could feed it into `OSCParser.parseOSCMessage()`, but that's a private function.

Surely there is a more direct way to do this. I'm starting to think casting the packet, as in the one bit of example code I've found, is the way, but Xcode still sees those as unrelated types.

**Comment by sammysmallman** [comment]
Hey @arlomedia,

Apologise for the delayed response. `OSCPacket` is now an enum with associated values. Rather than casting you can switch upon the object.

```swift
switch packet {
case let .bundle(bundle):
  print("Received: \(bundle)")
case let .message(message):
  print("Received: \(message)")
}
```

If you know you know you'll just be receiving OSC Messages you can do the following:
```swift
if case let .message(message) = packet {
  print("Received: \(message)")
}
```
