### ISSUE TITLE
Trouble extracting message from client using OSCKit on Xcode

### ISSUE THREAD

**Issue by allan1224** [sammysmallman/CoreOSC#2]
Hi, 

Basically I need help creating a handler for this specific address 

I'm having difficulty obtaining a single OSC message with a specific address pattern from a client. 
The client is called MindMonitor and I'm trying to stream EEG data to a UDP server on Xcode

The problem is that I want to extract a specific address: "/muse/eeg". The client app is sending data with multiple addresses, but I want to only read a specific one.  I can print the entire packet as a bundle, but because the client is sending multiple messages at multiple addresses, it's not always "/muse/eeg". 

EEG data: 
<img width="575" alt="Screen Shot 2022-04-24 at 5 43 31 PM" src="https://user-images.githubusercontent.com/7422344/165001147-5e7e67d2-4fb7-45eb-a668-8ff40f96b14e.png">

Gyro data:
<img width="558" alt="Screen Shot 2022-04-24 at 5 43 43 PM" src="https://user-images.githubusercontent.com/7422344/165001108-ba2efd05-1d44-4bf6-8da1-07e08ba10716.png">

When I try to create a message to read from a specific address: 
`let message1 = try! OSCMessage(with: "/muse/eeg")`
`print(message1)`

I get no data and empty arguments: 

<img width="546" alt="Screen Shot 2022-04-24 at 6 22 13 PM" src="https://user-images.githubusercontent.com/7422344/165001182-e63068af-6edd-439d-8a9e-79f39d4ff257.png">

I'm not really sure how OSC works exactly, but I just want to receive incoming messages with the specific address "/muse/eeg" and ignore all the other messages with other addresses. 

I'm using the OSCKit package in Xcode, but that repo said to direct questions about address patterns and stuff to this one. 

Any help/advice would be really appreciated. I've spent lots of time experimenting with the code and trying to solve this problem

Thanks!

**Comment by sammysmallman** [comment]
It looks like you're expecting an OSC Message when what you are receiving is an OSC Message within an OSC Bundle within another OSC Bundle.

You need to do some logic to extract the message from the bundles, something roughly like this...:
```swift
func server(_ server: OSCUdpServer,
            didReceivePacket packet: OSCPacket,
            fromHost host: String,
            port: UInt16) {
    guard let parentBundle = packet as? OSCBundle, 
          parentsBundle.elements.count == 1, 
          let childBundle = parentBundle.elements.first as? OSCBundle,
          childBundle.elements.count == 1,
          let message = childBundle.elements.first as? OSCMessage
    else { return }
    print(message.addressPattern)
}
```
